/**
 * GraduationLoop manages the core loop of PROTO, integrating perception, reasoning, and action.
 * It orchestrates the execution flow and ensures that each module communicates effectively.
 *
 * @module GraduationLoop
 */

const EventBus = require('./EventBus');
const PerceptionLoop = require('./PerceptionLoop');
const ModuleRegistry = require('./ModuleRegistry');
const DecisionMaker = require('../proto/reasoning/DecisionMaker');
const InputAdapter = require('../proto/perception/InputAdapter');

class GraduationLoop {
    constructor() {
        this.eventBus = new EventBus();
        this.perceptionLoop = new PerceptionLoop();
        this.decisionMaker = new DecisionMaker();
        this.inputAdapter = new InputAdapter();
    }

    /**
     * Starts the core loop of PROTO.
     */
    start() {
        this.eventBus.subscribe('inputReceived', this.processInput.bind(this));
        this.perceptionLoop.start();
        console.log('Graduation loop started. Listening for inputs...');
    }

    /**
     * Processes received input, triggering reasoning and acting.
     * @param {Object} input - The input object received from the input adapter.
     */
    processInput(input) {
        const perceivedData = this.inputAdapter.adaptInput(input);
        const decision = this.decisionMaker.makeDecision(perceivedData);
        this.actOnDecision(decision);
    }

    /**
     * Executes action based on the decision made.
     * @param {Object} decision - The decision object generated by the DecisionMaker.
     */
    actOnDecision(decision) {
        // Placeholder for action execution logic
        console.log(`Acting on decision: ${JSON.stringify(decision)}`);
    }

    /**
     * Stops the core loop of PROTO.
     */
    stop() {
        this.perceptionLoop.stop();
        console.log('Graduation loop stopped.');
    }
}

module.exports = GraduationLoop;