/**
 * PerceiveThinkActLoop - Main loop for PROTO's perception, reasoning, and action.
 *
 * This module orchestrates the perceive, think, and act cycle, allowing PROTO to process incoming signals,
 * reason about them, and execute actions based on the reasoning.
 *
 * @module PerceiveThinkActLoop
 */

const EventBus = require('./EventBus');
const ModuleRegistry = require('./ModuleRegistry');

class PerceiveThinkActLoop {
    constructor() {
        this.eventBus = new EventBus();
        this.modules = ModuleRegistry.getModules();
    }

    /**
     * Start the main loop for PROTO.
     * This method will continuously invoke the perceive, think, and act cycle.
     */
    start() {
        this.loop();
    }

    /**
     * The main loop, which processes the perceive, think, and act cycle at regular intervals.
     * @private
     */
    async loop() {
        while (true) {
            const signals = await this.perceive();
            const thoughts = await this.think(signals);
            await this.act(thoughts);
            await this.delay(100); // Delay to prevent a busy-wait loop
        }
    }

    /**
     * Perceive incoming signals by invoking the perception modules.
     * @returns {Promise<Array>} An array of signals
     */
    async perceive() {
        const signals = await this.modules.perception.processSignals();
        return signals;
    }

    /**
     * Think about the incoming signals using reasoning modules.
     * @param {Array} signals - The signals to reason about.
     * @returns {Promise<Object>} The results of reasoning
     */
    async think(signals) {
        const thoughts = await this.modules.reasoning.processThoughts(signals);
        return thoughts;
    }

    /**
     * Act based on the thoughts generated by the reasoning modules.
     * @param {Object} thoughts - The thoughts to act upon.
     */
    async act(thoughts) {
        await this.modules.voice.executeAction(thoughts);
    }

    /**
     * Delay execution for a specified amount of time.
     * @param {number} ms - The number of milliseconds to delay.
     * @returns {Promise<void>} A promise that resolves after the delay
     */
    delay(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }
}

module.exports = PerceiveThinkActLoop;